# Generated by Django 3.1.5 on 2021-01-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantrace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='file',
        ),
    ]
